# Copyright (C) Pipin Fitriadi - All Rights Reserved

# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Pipin Fitriadi <pipinfitriadi@gmail.com>, 28 June 2024

name: Github Page
on:
  push:
    branches: [main]
    paths:
      - src/**
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    name: Deploy Website
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Minify Website
        uses: docker://devatherock/minify-js:3.0.0
        with:
          directory: src/
          add_suffix: false
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
